 /******************************************************************************
 *
 * Module: HC-SR04
 *
 * File Name: Ultrasonic_Sensor.h
 *
 * Description: Header file for the AVR HC-SR04 driver
 *
 * Author: Belal Badr
 *
 *******************************************************************************/

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define Ultrasonic_division_factor   (58.8)

#define TRIGGER_PORT                 PORTB_ID
#define TRIGGER_PIN                  PIN5_ID

#define ECHO_PORT                    PORTD_ID
#define ECHO_PIN                     PIN6_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
* Description :
* Initialize the ICU driver as required.
* Setup the ICU call back function.
* Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void);

/*
* Description :
* Send the Trigger pulse to the Ultrasonic-sensor.
*/
void Ultrasonic_Trigger(void);

/*
* Description :
* Send the trigger pulse by using Ultrasonic_Trigger function.
* Start the measurements by the ICU from this moment.
* get the measured distance in centimeter.
*/
uint16 Ultrasonic_readDistance(void);

/*
* Description :
* This is the call-back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by the ultrasonic-sensor.
*/
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_SENSOR_H_ */
