 /******************************************************************************
 *
 * Module: HC-SR04
 *
 * File Name: Ultrasonic_Sensor.c
 *
 * Description: Source file for the AVR HC-SR04 driver
 *
 * Author: Belal Badr
 *
 *******************************************************************************/

#include "icu.h"
#include "gpio.h"
#include "Ultrasonic_Sensor.h"
#include <util/delay.h>
#include <math.h>
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
extern Icu_ConfigType Config_obj;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
* Description :
* Initialize the ICU driver as required.
* Setup the ICU call back function.
* Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void)
{
	/* Initialize the configuration type for ICU */
	Config_obj.clock = F_CPU_8;
	Config_obj.edge = RISING;

	/* Initialize the ICU driver as required */
	Icu_init(&Config_obj);

	/* Setup the ICU call back function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*  Setup the direction for the trigger & echo pin through the GPIO driver */
	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, PIN_OUTPUT);
	GPIO_setupPinDirection(ECHO_PORT, ECHO_PIN, PIN_INPUT);
}


/*
* Description :
* Send the Trigger pulse to the Ultrasonic-sensor.
*/
void Ultrasonic_Trigger(void)
{
	/* Setting the Trigger pin on LOGIC_HIGH for 15 us in order to generate the required Echo */
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_HIGH);
	_delay_us(15);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);
}


/*
* Description :
* Send the trigger pulse by using Ultrasonic_Trigger function.
* Start the measurements by the ICU from this moment.
* get the measured distance in centimeter.
*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 real_distance;
	/* Send the trigger pulse by using Ultrasonic_Trigger function */
	Ultrasonic_Trigger();

	/* wait until the edge count become 2 so we can obtain Time_High */
	while(1)
	{
		/* wait until it becomes 2 */
		if(g_edgeCount == 2)
		{
			g_edgeCount = 0;

			/* calculate the Distance */
			real_distance = round(g_timeHigh/Ultrasonic_division_factor) ;
			return real_distance;
		}
	}
}

/*
* Description :
* This is the call-back function called by the ICU driver.
* This is used to calculate the high time (pulse time) generated by the ultrasonic-sensor.
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
		if(g_edgeCount == 1)
		{
			/*
			 * Clear the timer counter register to start measurements from the first detected rising edge
			 */
			Icu_clearTimerValue();
			/* Detect falling edge */
			Icu_setEdgeDetectionType(FALLING);
		}
		else if(g_edgeCount == 2)
		{
			/* Store the High time value */
			g_timeHigh = Icu_getInputCaptureValue();
			/* Detect rising edge */
			Icu_setEdgeDetectionType(RISING);
		}
}
